### ISSUE TITLE
Acknowledge copyright holder when copying code

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-R/usgs-r.github.com#10]
The index.html is copied and modified from twitter.github.com, which holds the copyright on that code.  This should be acknowledged in the source of that file since the LICENSE with that repo is not copied along.  This is important when copying code from elsewhere that we acknowledge and convey the licensing.

**Comment by jread-usgs** [comment]
@mwernimont can you take care of this?

**Comment by mwernimont** [comment]
@jiwalker-usgs So say //code is copied and modified from twitter.github.com?

**Comment by lawinslow** [comment]
I think you just need to bring [this LICENSE](https://github.com/twitter/twitter.github.com/blob/master/LICENSE) file along.

**Comment by jiwalker-usgs** [comment]
If you read section 4 of the LICENSE file, it says that you need to redistribute the original license, make it clear where you are making modifications (big comment at the top of the modified file), and a couple other measures to be compliant.

**Comment by jiwalker-usgs** [comment]
I think this is good.  LICENSE is redistributed and comment is in modified source file.  If you change any of their CSS (may want to cascade instead) be sure to include a disclaimer there as well.
