### ISSUE TITLE
USGS employees without Admin rights

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/usgs-r.github.com#45]
From an email:

1. For today's installation, R studio defaulted to storing all data, workspaces, etc. in My Documents. (Huh?) When I started R studio and noticed that it was set to dump everything into My Documents, I choose "New Project" in an "existing directory" and picked an "R resources" folder that I had created earlier on the my networked area that gets backed up. I hope this was the ideal choice. (If it's not, please let me know.) It might be good to provide guidance on the need to set up a project directory early for R studio (upon first opening) before it spawns offspring into a person's "My Documents" folder. 

2. The software itself (R and R Studio) got correctly oriented to Programs Files when the installation was done using the "Run as Administrator" option. (An initial installation not as administrator gave the appearance of working but had problems with permissions and the directory structure, so we had to uninstall everything and start over.)

3. Should I have picked 32-bit or 64-bit and why? My Windows is 64-bit, so we installed R as 64-bit, but I noticed that a few packages mention the need to use 32-bit.

4. A nice thing about the out-dated BWTST installation instructions is the screen shots for the permission setting steps. I don't have a -PR account, so I was relying on the USGS Service Desk staff to do the installation, and they're not fluent in the process. (I'm not fluent in the process either, but I could point them to the pictures.)

**Comment by lawinslow** [comment]
New introR has instructions on this
http://usgs-r.github.io/introR/2015/01/14/00-Before-The-Workshop/

If we'd like, we can link directly to that from owi/R. 

As for number 4, I don't want to recommend that permission change. There are almost no advantages when packages are up on CRAN/GRAN and several disadvantages to that technique.

**Comment by ldecicco-USGS** [comment]
R installs just fine, and packages install to the User lib just fine without pr access. RStudio needs admin access. (playing with a 'fresh' computer)

**Comment by ldecicco-USGS** [comment]
Also probably want to have Service Desk install latex tools (agree? disagree?)

**Comment by dlorenz-usgs** [comment]
I agree, if the user never uses it, it just takes up a small amount of
space and if the user wants it, it is available.
