### ISSUE TITLE
USGSws* Packages

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/usgs-r.github.com#47]
Can we drop the USGSws* packages from here? There are still a lot of old instructions scattered about that tell people to install these packages. This can create a great deal of confusion for students when they are learning about dataRetrieval and the smwr* packages.

**Comment by jread-usgs** [comment]
:+1: to minimizing confusion

**Comment by dlorenz-usgs** [comment]
No, it will cause other packages (rloadest, restrend and DVstats) to fail
if the user cannot load the USGSws... packages. I am working on getting
them updated. rloadest is now, but it takes time.

**Comment by lawinslow** [comment]
Ah, ok. I'll leave this up here though. We will want to get that stuff down as those packages are updated.

**Comment by dlorenz-usgs** [comment]
I'd hope to get all caught up for R 3.2 so that the USGSws... packages will
not be supported for taht version.
